### PR TITLE
Instituttlederforum presentation

### PR DESCRIPTION
**Pull request by gregordecristoforo**
Here is my draft presentation for the Instituttlederforum. Let me know what you think.

### CODE REVIEW

**Comment by bast** [comment]
Rendered version: https://cicero.xyz/v3/remark/0.14.0/github.com/gregordecristoforo/rse-presentations/Instituttlederforum/Instituttlederforum.md/

**Comment by bast** [comment]
- Slide 3, I would zoom in on the blue part. Too tiny to read.
- I would change the name and not call it "Instituttlederforum" since we will reuse it outside
- I would replace the short slidedeck or the long one with your version. It's better and better we have not too many diverging ones.

**Comment by gregordecristoforo** [comment]
Done, are there any other comments you might have?

**Comment by bast** [comment]
Thanks! All good. Is the "short" file now the same as the Instituttlederforum one? In any case just merge and we fix later.

**Comment by gregordecristoforo** [comment]
Yes it is the "short" one, I will delete the duplicate files

**Pull request merged**
